export const FANS = [
  { name: "大四喜", points: 88, group: "字牌系列", description: "由东、南、西、北四副风刻或风杠组成的和牌。", excludes: "小四喜、三风刻、碰碰和、圈风刻、门风刻、幺九刻" },
  { name: "大三元", points: 88, group: "字牌系列", description: "和牌中有中、发、白三副箭刻或箭杠。", excludes: "小三元、双箭刻、箭刻" },
  { name: "绿一色", points: 88, group: "花色组合系列", description: "只由二、三、四、六、八条及发组成的和牌。", excludes: "混一色" },
  { name: "九莲宝灯", points: 88, group: "特殊系列", description: "一种花色的 1112345678999，再加同花色任意一张。", excludes: "清一色、门前清、不求人、幺九刻" },
  { name: "四杠", points: 88, group: "杠牌系列", description: "四个杠与将牌组成的和牌。", excludes: "三杠、双暗杠、双明杠、碰碰和、单钓将" },
  { name: "连七对", points: 88, group: "七对系列", description: "一种花色中，序数连续的七个对子。", excludes: "七对、清一色、平和" },
  { name: "十三幺", points: 88, group: "特殊系列", description: "三种序数牌的一九、七种字牌，以及其中一对作将。", excludes: "五门齐、门前清、不求人、单钓将" },

  { name: "清幺九", points: 64, group: "刻牌系列", description: "只由序数牌一、九的刻子、顺子及将牌组成。", excludes: "碰碰和、混幺九、幺九刻、无字" },
  { name: "小四喜", points: 64, group: "字牌系列", description: "三副风刻或风杠，另以风牌作将。", excludes: "大四喜、三风刻" },
  { name: "小三元", points: 64, group: "字牌系列", description: "两副箭刻或箭杠，另以箭牌作将。", excludes: "大三元、双箭刻、箭刻" },
  { name: "字一色", points: 64, group: "字牌系列", description: "全部由字牌的刻子、杠和将牌组成。", excludes: "碰碰和" },
  { name: "四暗刻", points: 64, group: "刻牌系列", description: "四个暗刻或暗杠组成的和牌。", excludes: "门前清、碰碰和、不求人" },
  { name: "一色双龙会", points: 64, group: "老少系列", description: "一种花色的两个 123、两个 789，五作将。", excludes: "老少副、一般高、清一色、平和、缺一门" },

  { name: "一色四同顺", points: 48, group: "同顺系列", description: "同一花色有四副起首相同的顺子。", excludes: "一色三同顺、一般高、四归一" },
  { name: "一色四节高", points: 48, group: "刻牌系列", description: "同一花色有四副依次递增一位的刻子或杠。", excludes: "一色三节高、碰碰和" },

  { name: "一色四步高", points: 32, group: "步步高系列", description: "同一花色四副顺子按一位或两位递增。", excludes: "一色三步高" },
  { name: "三杠", points: 32, group: "杠牌系列", description: "和牌中有三个杠。", excludes: "双明杠、双暗杠" },
  { name: "混幺九", points: 32, group: "刻牌系列", description: "由字牌与序数牌一、九的刻子、顺子及将牌组成。", excludes: "清幺九、碰碰和、幺九刻" },

  { name: "七对", points: 24, group: "七对系列", description: "由七个对子组成的和牌。", excludes: "门前清、不求人、单钓将" },
  { name: "七星不靠", points: 24, group: "不靠系列", description: "七种字牌各一张，加三种花色 147、258、369 组合出的七张序数牌。", excludes: "五门齐、全不靠、不求人、单钓将" },
  { name: "全双刻", points: 24, group: "刻牌系列", description: "全部由二、四、六、八的刻子和将牌组成。", excludes: "碰碰和、断幺" },
  { name: "清一色", points: 24, group: "花色组合系列", description: "和牌全部属于同一种序数牌花色。", excludes: "无字" },
  { name: "一色三同顺", points: 24, group: "同顺系列", description: "同一花色有三副起首相同的顺子。", excludes: "一色三节高、一般高" },
  { name: "一色三节高", points: 24, group: "刻牌系列", description: "同一花色有三副依次递增一位的刻子或杠。", excludes: "一色三同顺" },
  { name: "全大", points: 24, group: "序数牌系列", description: "只由七、八、九组成顺子、刻子或将牌。", excludes: "大于五" },
  { name: "全中", points: 24, group: "序数牌系列", description: "只由四、五、六组成顺子、刻子或将牌。", excludes: "断幺" },
  { name: "全小", points: 24, group: "序数牌系列", description: "只由一、二、三组成顺子、刻子或将牌。", excludes: "小于五" },

  { name: "清龙", points: 16, group: "龙系列", description: "同一花色的 123、456、789 三副顺子。", excludes: "连六" },
  { name: "三色双龙会", points: 16, group: "老少系列", description: "两种花色各有 123、789，第三种花色以五作将。", excludes: "喜相逢、平和、无字" },
  { name: "一色三步高", points: 16, group: "步步高系列", description: "同一花色三副顺子按一位或两位递增。", excludes: "" },
  { name: "全带五", points: 16, group: "全带系列", description: "每副牌和将牌都含有序数牌五。", excludes: "断幺" },
  { name: "三同刻", points: 16, group: "刻牌系列", description: "三种花色中有三副相同序数的刻子或杠。", excludes: "双同刻" },
  { name: "三暗刻", points: 16, group: "刻牌系列", description: "三个暗刻或暗杠。", excludes: "双暗刻" },

  { name: "全不靠", points: 12, group: "不靠系列", description: "三种花色的 147、258、369 单张与字牌中的任意单张组成和牌。", excludes: "五门齐、不求人、单钓将" },
  { name: "组合龙", points: 12, group: "龙系列", description: "三种花色分别组成 147、258、369 的三组单张。", excludes: "" },
  { name: "大于五", points: 12, group: "序数牌系列", description: "只由六至九的序数牌组成和牌。", excludes: "无字" },
  { name: "小于五", points: 12, group: "序数牌系列", description: "只由一至四的序数牌组成和牌。", excludes: "无字" },
  { name: "三风刻", points: 12, group: "字牌系列", description: "三副风刻或风杠。", excludes: "" },

  { name: "花龙", points: 8, group: "龙系列", description: "三种花色各一副顺子，连接成 1 至 9。", excludes: "一般高、平和" },
  { name: "推不倒", points: 8, group: "特殊系列", description: "只使用牌面图形上下对称的序数牌及白板。", excludes: "缺一门" },
  { name: "三色三同顺", points: 8, group: "同顺系列", description: "三种花色各有一副起首相同的顺子。", excludes: "喜相逢" },
  { name: "三色三节高", points: 8, group: "刻牌系列", description: "三种花色各有刻子，序数依次递增一位。", excludes: "" },
  { name: "无番和", points: 8, group: "和牌方式系列", description: "和牌后没有其他可计番种，花牌不计入此判断。", excludes: "" },
  { name: "妙手回春", points: 8, group: "和牌方式系列", description: "自摸牌墙最后一张牌和牌，不另计自摸。", excludes: "自摸" },
  { name: "海底捞月", points: 8, group: "和牌方式系列", description: "和牌于牌墙最后一张打出的牌。", excludes: "" },
  { name: "杠上开花", points: 8, group: "和牌方式系列", description: "开杠后抓进的牌成和，不包括补花。", excludes: "自摸" },
  { name: "抢杠和", points: 8, group: "和牌方式系列", description: "和别人开明杠时所抢的那张牌。", excludes: "和绝张" },

  { name: "碰碰和", points: 6, group: "刻牌系列", description: "四副牌全部为刻子或杠。", excludes: "" },
  { name: "混一色", points: 6, group: "花色组合系列", description: "一种序数牌花色与字牌组成和牌。", excludes: "" },
  { name: "三色三步高", points: 6, group: "步步高系列", description: "三种花色的三副顺子按一位递增。", excludes: "" },
  { name: "五门齐", points: 6, group: "花色组合系列", description: "三种序数牌、风牌、箭牌五类牌齐全。", excludes: "" },
  { name: "全求人", points: 6, group: "和牌方式系列", description: "全靠吃、碰、杠后单钓他人打出的牌和牌。", excludes: "单钓将" },
  { name: "双暗杠", points: 6, group: "杠牌系列", description: "两个暗杠。", excludes: "" },
  { name: "双箭刻", points: 6, group: "字牌系列", description: "两副箭刻或箭杠。", excludes: "" },

  { name: "全带幺", points: 4, group: "全带系列", description: "每副牌和将牌都含有幺九牌或字牌。", excludes: "" },
  { name: "不求人", points: 4, group: "和牌方式系列", description: "没有吃、碰、明杠，并以自摸和牌。", excludes: "" },
  { name: "双明杠", points: 4, group: "杠牌系列", description: "两个明杠。", excludes: "" },
  { name: "和绝张", points: 4, group: "和牌方式系列", description: "和牌张是牌池、桌面已亮出的三张之外的第四张。", excludes: "抢杠和" },

  { name: "箭刻", points: 2, group: "字牌系列", description: "中、发、白任一副刻子或箭杠。", excludes: "" },
  { name: "圈风刻", points: 2, group: "字牌系列", description: "与当前圈风相同的风刻或风杠。", excludes: "" },
  { name: "门风刻", points: 2, group: "字牌系列", description: "与本门风相同的风刻或风杠。", excludes: "" },
  { name: "门前清", points: 2, group: "和牌方式系列", description: "没有吃、碰、明杠，并和他人打出的牌。", excludes: "" },
  { name: "平和", points: 2, group: "和牌方式系列", description: "四副顺子与序数牌将组成的和牌。", excludes: "无字" },
  { name: "四归一", points: 2, group: "刻牌系列", description: "同一张牌的四张归在一家和牌组合内，杠牌不计。", excludes: "" },
  { name: "双同刻", points: 2, group: "刻牌系列", description: "两副序数相同的刻子或杠。", excludes: "" },
  { name: "双暗刻", points: 2, group: "刻牌系列", description: "两个暗刻或暗杠。", excludes: "" },
  { name: "暗杠", points: 2, group: "杠牌系列", description: "自抓四张相同的牌开杠。", excludes: "" },
  { name: "断幺", points: 2, group: "序数牌系列", description: "和牌中没有一、九及字牌。", excludes: "" },

  { name: "一般高", points: 1, group: "同顺系列", description: "同一花色有两副相同的顺子。", excludes: "" },
  { name: "喜相逢", points: 1, group: "同顺系列", description: "两种花色有两副序数相同的顺子。", excludes: "" },
  { name: "连六", points: 1, group: "龙系列", description: "同一花色有六张序数相连。", excludes: "" },
  { name: "老少副", points: 1, group: "老少系列", description: "同一花色有 123 和 789 两副顺子。", excludes: "" },
  { name: "幺九刻", points: 1, group: "刻牌系列", description: "一、九或风牌组成的刻子或杠。", excludes: "" },
  { name: "明杠", points: 1, group: "杠牌系列", description: "吃碰后以外来牌组成的明杠。", excludes: "" },
  { name: "缺一门", points: 1, group: "花色组合系列", description: "和牌中缺少一种序数牌花色。", excludes: "" },
  { name: "无字", points: 1, group: "花色组合系列", description: "和牌中没有风牌和箭牌。", excludes: "" },
  { name: "边张", points: 1, group: "和牌方式系列", description: "和 123 的三或 789 的七形成的边张。", excludes: "" },
  { name: "坎张", points: 1, group: "和牌方式系列", description: "和顺子中间缺少的那张牌。", excludes: "" },
  { name: "单钓将", points: 1, group: "和牌方式系列", description: "单和一张牌组成将牌。", excludes: "" },
  { name: "自摸", points: 1, group: "和牌方式系列", description: "自己抓进牌成和。", excludes: "" },
  { name: "花牌", points: 1, group: "特殊系列", description: "春夏秋冬、梅兰竹菊，每张计一番，不计入起和。", excludes: "不计入起和" },
];

export const FAN_POINTS = [...new Set(FANS.map((fan) => fan.points))].sort((a, b) => b - a);
